# Generated by Django 5.2.6 on 2025-09-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.URLField(help_text='URL gambar produk'),
        ),
    ]
